#!/bin/bash

if ! command -v stow &> /dev/null
then
    echo "command 'stow' not found"
    echo "install it with 'apt install stow'"
    exit
fi

#stow --target=$HOME bash
#stow --target=$HOME vim
stow --target=$HOME nvim
stow --target=$HOME zsh
#stow --target=$HOME ranger

