#!/bin/bash

if [ $(xinput list "ETPS/2 Elantech Touchpad" | head -n 1 | awk '{print $4}' | sed 's/id=//') != '19' ];then
    exit 0
fi

if [ $(xinput --list-props 19 | head -n 2 | tail -n 1 | awk '{print $4}') == '1' ];then
    # disable touchpad
    xinput disable 19
else
    # enable touchpad
    xinput enable 19
fi
