#!/bin/bash

if ! command -v stow &> /dev/null
then
    echo "command 'stow' not found"
    echo "install it with 'pacman -S stow'"
    exit
fi

echo "stow: shell"
stow --target=$HOME shell
#echo "stow: zsh"
#stow --target=$HOME zsh
echo "stow: fish"
stow --target=$HOME fish
echo "stow: nvim-lua"
stow --target=$HOME nvim.lua
echo "stow: redshift"
stow --target=$HOME redshift
echo "redshift: systemctl enable"
systemctl --user enable redshift.service
echo "stow: i3"
stow --target=$HOME i3
echo "stow: py3status"
stow --target=$HOME py3status
echo "stow: alacritty"
stow --target=$HOME alacritty
echo "stow: picom"
stow --target=$HOME picom
