{
  imports = [
    ./ai.nix
    ./btrfs.nix
    ./cron.nix
    ./desktop.nix
    ./file-manager.nix
    ./flatpak.nix
    ./fonts.nix
    ./gaming.nix
    ./libinput.nix
    ./mouse.nix
    ./openssh.nix
    ./polkit.nix
    ./power.nix
    ./printer.nix
    ./smartd.nix
    ./sound.nix
    ./virtualization.nix
  ];
}
