{
  imports = [
    ./ai.nix
    ./btrfs.nix
    ./file-manager.nix
    ./fonts.nix
    ./gaming.nix
    ./gparted.nix
    ./libinput.nix
    ./login-manager.nix
    ./lvm.nix
    ./mouse.nix
    ./openssh.nix
    ./polkit.nix
    ./power.nix
    ./printer.nix
    ./smartd.nix
    ./sound.nix
    ./xserver.nix
    ./zfs.nix
  ];
}
