# Show help message
default:
    @just --list

# Build and activate the new configuration (no add it to boot)
test:
    nh os test --ask

# Build and activate the new configuration with verbose logging
test-verbose:
    nh os test --verbose

# Build the new configuration and make it the boot default (no activate)
boot:
    nh os boot --ask

# Build and activate the new configuration and make it the boot default
switch:
    nh os switch --ask

# Run system update
update:
    nh os switch --update --ask

# Run system update with no user interaction
update-no-ask:
    nh os switch --update

# Run NixOS rebuild switch upgrade
nixos-update:
    sudo nixos-rebuild switch --upgrade

# Delete all generations older than TIME
clean TIME: gc
    sudo nix-collect-garbage --delete-older-than {{TIME}}

# Keep NUMBER generations
keep NUMBER: gc
    nh clean all --keep {{NUMBER}}

# Delete all old generations
prune: gc
    sudo nix-collect-garbage --delete-old

# Replace identical files in the store by hard links
optimise:
    nix store optimise

# Perform garbage collection on a Nix store
gc:
    nix store gc

# List all generations
list:
    sudo nix-env -p /nix/var/nix/profiles/system/ --list-generations

# Format Nix configuration
format:
    fd -e nix -X nixfmt {}
