# Show help message
default:
    @just --list

# Build and activate the new configuration (no add it to boot)
test:
    nh os test --ask

# Build the new configuration and make it the boot default (no activate)
boot:
    nh os boot --ask

# Build and activate the new configuration and make it the boot default
switch:
    nh os switch --ask

# Run nh os switch update
update:
    nh os switch --update --ask

# Delete all generations older than TIME
clean TIME: gc
    sudo nix-collect-garbage --delete-older-than {{TIME}}

# Delete all old generations
prune: gc
    sudo nix-collect-garbage --delete-old

# Run nix store optimize
optimise:
    nix store optimise

# Run nix store gc
gc:
    nix store gc

# List all generations
list:
    sudo nix-env -p /nix/var/nix/profiles/system/ --list-generations

# Format Nix configuration
format:
    fd -e nix -X nixfmt {}
