#!/bin/bash

if ! command -v stow &> /dev/null
then
    echo "command 'stow' not found"
    echo "install it with 'pacman -Sy stow'"
    exit
fi

#stow --target=$HOME vim
stow --target=$HOME nvim
stow --target=$HOME zsh
stow --target=$HOME i3
#stow --target=$HOME i3status
stow --target=$HOME py3status
stow --target=$HOME Xresources
stow --target=$HOME redshift
#stow --target=$HOME ranger
sudo stow --target=/usr/local/bin scripts
