# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ehci_pci"
    "ahci"
    "usb_storage"
    "sd_mod"
    "sr_mod"
    "rtsx_pci_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/mapper/crypthddsystem";
    fsType = "btrfs";
    options = [
      "subvol=@"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  boot.initrd.luks.devices."crypthddsystem".device =
    "/dev/disk/by-uuid/b9379ba6-a740-466b-b879-d044822a77aa";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/f7e07e16-f065-49b6-8a65-5f38d10decc8";
    fsType = "ext4";
  };

  fileSystems."/boot/efi" = {
    device = "/dev/disk/by-uuid/6533-23A6";
    fsType = "vfat";
    options = [
      "fmask=0022"
      "dmask=0022"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/mapper/crypthddsystem";
    fsType = "btrfs";
    options = [
      "subvol=@home"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/crypthddsystem";
    fsType = "btrfs";
    options = [
      "subvol=@nix"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  fileSystems."/var" = {
    device = "/dev/mapper/crypthddsystem";
    fsType = "btrfs";
    options = [
      "subvol=@var"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
    ];
  };

  boot.initrd.luks.devices."cryptssdsystem".device =
    "/dev/disk/by-uuid/0a64c059-5368-4b2f-814f-eafd11e92eaf";
  boot.initrd.luks.devices."cryptssdswap".device =
    "/dev/disk/by-uuid/d1962db4-c3d7-42e2-bc5a-6b6fe65d0c3f";

  fileSystems."/var/cache" = {
    device = "/dev/mapper/cryptssdsystem";
    fsType = "btrfs";
    options = [
      "subvol=@var-cache"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/mapper/cryptssdsystem";
    fsType = "btrfs";
    options = [
      "subvol=@var-tmp"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
      "ssd"
      "discard=async"
    ];
  };

  fileSystems."/var/log" = {
    device = "/dev/mapper/cryptssdsystem";
    fsType = "btrfs";
    options = [
      "subvol=@var-log"
      "noatime"
      "compress=zstd"
      "space_cache=v2"
      "ssd"
      "discard=async"
    ];
  };

  swapDevices = [
    {
      device = "/dev/mapper/cryptssdswap";
      priority = 10;
    }
  ];

  zramSwap = {
    enable = true;
    memoryPercent = 50;
    algorithm = "zstd";
    priority = 100;
  };

  boot.kernel.sysctl = {
    "vm.swappiness" = 10;
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
