-- Scripts that runs AFTER all main Lua scripts
-- (useful to configure installed plugins)
-- (the require instructions are executed in order)
-- base16-colorscheme config
-- require("modules.base16")
